version: "3.7"
services:

  postgres:
    image: postgres:14.7
    env_file:
      - app/config/.env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app -d users_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - cache:/data

  app:
    restart: "no"
    image: app_image
    build:
      context: .
    env_file:
      - app/config/.env
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"

volumes:
  cache:
    driver: local