"""add on_delete cascade

Revision ID: 541f2010ad7d
Revises: 529d59a2102c
Create Date: 2023-06-18 19:38:31.152880

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '541f2010ad7d'
down_revision = '529d59a2102c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('roles_users_user_id_fkey', 'roles_users', type_='foreignkey')
    op.drop_constraint('roles_users_role_id_fkey', 'roles_users', type_='foreignkey')
    op.create_foreign_key(None, 'roles_users', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'roles_users', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('social_account_user_id_fkey', 'social_account', type_='foreignkey')
    op.create_foreign_key(None, 'social_account', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_session_user_id_fkey', 'user_session', type_='foreignkey')
    op.create_foreign_key(None, 'user_session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_session', type_='foreignkey')
    op.create_foreign_key('user_session_user_id_fkey', 'user_session', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'social_account', type_='foreignkey')
    op.create_foreign_key('social_account_user_id_fkey', 'social_account', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.drop_constraint(None, 'roles_users', type_='foreignkey')
    op.create_foreign_key('roles_users_role_id_fkey', 'roles_users', 'role', ['role_id'], ['id'])
    op.create_foreign_key('roles_users_user_id_fkey', 'roles_users', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
