"""create tiny url table and confirm email

Revision ID: b3d153423a99
Revises: 541f2010ad7d
Create Date: 2023-11-15 18:44:05.433960

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'b3d153423a99'
down_revision = '541f2010ad7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiny_urls',
    sa.Column('full_url', sa.String(length=255), nullable=False),
    sa.Column('short_url', sa.String(length=10), nullable=False),
    sa.Column('requests_count', sa.Integer(), nullable=True, default=0),
    sa.Column('created_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('short_url'),
    sa.UniqueConstraint('full_url'),
    sa.UniqueConstraint('short_url')
    )
    op.add_column('user', sa.Column('email_is_confirmed', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_is_confirmed')
    op.drop_table('tiny_urls')
    # ### end Alembic commands ###
