name: Generate changelog

on:
  push:
    branches:
      - 'main'

jobs: 
 generate-changelog:
  runs-on: ubuntu-latest
  steps:
  - name: Calculate release version
    run: |
      echo "release_version=1.$(date +'%g%m%d%H%M').0" >> $GITHUB_ENV
  - name: Changelog
    uses: ardalanamini/auto-changelog@v4
    id: changelog
    with:
      github-token: ${{ github.token }}
      commit-types: |
          breaking: Breaking Changes
          feat: New Features
          fix: Bug Fixes
          revert: Reverts
          perf: Performance Improvements
          refactor: Refactors
          deps: Dependencies
          docs: Documentation Changes
          style: Code Style Changes
          build: Build System
          ci: Continuous Integration
          test: Tests
          chore: Chores
          other: Other Changes
      default-commit-type: Other Changes
      release-name: v${{ env.release_version }}
      mention-authors: true
      mention-new-contributors: true
      semver: true
  - name: Save to Changelog.md
    run: echo "${{ steps.changelog.outputs.changelog }}" > changelog.md
  - name: Add and commit
    uses: EndBug/add-and-commit@v9
    with:
      message: 'other: update changelog [ignore]'
      add: 'changelog.md'
      default_author: github_actions
