name: Generate changelog

on:
  push:
    branches:
      - 'main'

jobs: 
 generate-changelog:
  runs-on: ubuntu-latest
  steps:
    - name: Changelog
      uses: ardalanamini/auto-changelog@v4
      id: changelog
